## parameter and error terms used throughout
set.seed(123)
a = matrix(c(0.5, 0.1, 0.1, 0.5), nrow = 2)
u = matrix(rnorm(10000), ncol = 2)

# Lets start with the R version
rSim = function(coef, errors) {
  simdata = matrix(0, nrow(errors), ncol(errors))
  for (row in 2:nrow(errors)) {
    simdata[row,] = coef %*% simdata[(row - 1),] + errors[row, ]
  }
  return(simdata)
}

rData = rSim(a, u) #generated by R